parser: "babel-eslint"
env:
    commonjs: true
    node: true
    es6: true

parserOptions:
    ecmaVersion: 6
    sourceType: module

rules:

    # Possible Errors
    for-direction: 2
    getter-return: 2
    no-cond-assign: 2
    no-control-regex: 2
    no-duplicate-case: 2
    no-unexpected-multiline: 2
    no-template-curly-in-string: 2
    no-func-assign: 2
    no-unreachable: 2
    no-constant-condition: 2
    no-dupe-args: 2
    no-dupe-keys: 2
    no-await-in-loop: 1
    no-debugger: 1
    no-empty: 1
    no-invalid-regexp: 1
    no-extra-semi: 1
    no-ex-assign: 1
    no-prototype-builtins: 1
    no-regex-spaces: 1
    no-extra-boolean-cast: 1
    no-unsafe-negation: 1
    no-extra-parens:
        - warn
        - all

    # Best Practices
    block-scoped-var: 2
    eqeqeq: 2
    no-caller: 2
    no-alert: 2
    no-empty-function: 2
    no-loop-func: 2
    no-extend-native: 2
    no-new-func: 2
    no-new-wrappers: 2
    no-new: 2
    no-lone-blocks: 2
    no-iterator: 2
    no-invalid-this: 2
    no-extra-bind: 2
    no-redeclare: 2
    no-proto: 2
    no-return-assign: 2
    no-return-await: 2
    no-self-compare: 2
    no-self-assign: 2
    no-unused-expressions: 2
    no-useless-return: 2
    no-useless-escape: 2
    no-useless-concat: 2
    no-useless-call: 2
    require-await: 2
    consistent-return: 2
    no-empty-pattern: 2
    no-fallthrough: 2
    no-labels: 2
    no-sequences: 2
    no-throw-literal: 2
    no-unmodified-loop-condition: 2
    no-with: 2

    prefer-promise-reject-errors: 1
    no-magic-numbers: 1
    no-multi-spaces: 1
    no-global-assign: 1
    accessor-pairs: 1
    array-callback-return: 1
    no-case-declarations: 1
    default-case: 1
    no-eval: 1
    class-methods-use-this: 1
    no-floating-decimal: 1
    curly: 1
    no-implicit-coercion: 1
    dot-location: 1
    dot-notation: 1

    # Variables
    no-undef-init: 2
    no-undef: 2
    no-use-before-define: 2
    no-unused-vars: 2

    # Node.js and CommonJS
    global-require: 2
    no-mixed-requires: 2
    handle-callback-err: 2
    no-path-concat: 2
    no-new-require: 2

    # Stylistic Issues
    array-bracket-spacing: 2
    block-spacing: 2
    camelcase: 2
    computed-property-spacing: 2
    no-unneeded-ternary: 2
    no-new-object: 2
    no-multiple-empty-lines: 2
    no-mixed-spaces-and-tabs: 2
    no-array-constructor: 2
    comma-spacing: 2
    brace-style: 2
    indent: 2
    implicit-arrow-linebreak: 2
    lines-between-class-members: 2
    sort-vars: 2
    operator-assignment: 2
    spaced-comment: 2
    object-curly-spacing:
        - error
        - always
    padded-blocks:
        - error
        - never
    operator-linebreak:
        - warn
        - before
    space-unary-ops:
        - error
        -   words: true
            nonwords: false

    # ECMAScript 6
    arrow-spacing: 2
    constructor-super: 2
    no-dupe-class-members: 2
    no-const-assign: 2
    no-class-assign: 2
    no-duplicate-imports: 2
    no-this-before-super: 2
    no-useless-computed-key: 2
    prefer-const: 2
    prefer-arrow-callback: 2
    no-var: 2
    prefer-numeric-literals: 2
    prefer-spread  : 2
    prefer-rest-params: 2
    no-useless-constructor: 2
    object-shorthand: 2
    prefer-destructuring: 2
    prefer-template: 2
    rest-spread-spacing: 2
    template-curly-spacing: 2