language: node_js
node_js:
  - "node"
  - "6"
before_script:
  - "npm run build"
after_success:
  - "npm run coveralls"
jobs:
  include:
    - stage: test
      script: "npm run lint"
      script: "npm run mocha"
      script: "npm run test-coverage"
notifications:
  email:
    recipients: dipustovit@gmail.com
    on_success: change
    on_failure: always